Replace environment variables with arguments
paulgmiller/vstsdropdownloadcore pull request #6
Opened 2018-05-29 20:04 UTC by stshrive

Add simple argument parser

2018-05-29 20:05 UTC, stshrive commented
@paulgmiller, this requires a change to the release definition for it to run. This branch is currently hosted at [stshriv/vstsdropdownloadcore](https://hub.docker.com/r/stshriv/vstsdropdownloadcore/) on docker hub

2018-06-04 16:57 UTC, paulgmiller commented on Args.cs
> +        public void Parse(string[] args)
any reason you didn't just use. https://www.nuget.org/packages/CommandLineParser/

2018-06-04 16:58 UTC, paulgmiller commented on Program.cs
> +            dropdownloadcore.Args arguments = new dropdownloadcore.Args();
we can just default these to the env vars

2018-06-04 16:59 UTC, paulgmiller requested changes
fine with what you're doing except I don't like custom arg parsign and want to fall back to default.

2018-06-04 17:35 UTC, stshrive commented
I din't wan't to pull in a dependency on a full argument parser. It can be removed if you'd like.

2018-06-04 21:53 UTC, paulgmiller commented on Args.cs
> +        public void CheckEnvironmentVariables()
so you could not do the arg checks if you instead make this a static Args FromEnvVars() {} method and use it to create your args.

2018-06-04 21:54 UTC, paulgmiller commented on Args.cs
> +        public void CheckEnvironmentVariables()
then remove it from parse

2018-06-04 21:55 UTC, paulgmiller commented on Args.cs
> +            this.ValidatePat();
maybe shouldn't be part of parse?

2018-06-04 23:50 UTC, paulgmiller approved these changes

2018-06-05 05:42 UTC, merged